### PR TITLE
Adds Flow extension

### PR DESCRIPTION
**Pull request by vedmaka**
Don't merge, please, this conflicts with https://github.com/CanastaWiki/Canasta/pull/270

https://www.mediawiki.org/wiki/Extension:StructuredDiscussions

### CODE REVIEW

**Comment by yaronkoren** [comment]
Before you do any more work on this patch: I think I can say with pretty high confidence that the Flow/StructuredDiscussions extension will never get added to Canasta. It is barely maintained at this point, and the DiscussionTools extension is a superior solution in just about every way. In fact, I dare say that any Canasta-based wiki that is using StructuredDiscussions should switch off of it, if at all possible. (If there are already many messages within the SD system, that's a problem - hopefully at some point the WMF will create a tool to convert these threads to regular talk pages, but I don't think they have yet.)

**Comment by vedmaka** [comment]
Yes, the [DiscussionTools](https://www.mediawiki.org/wiki/Extension:DiscussionTools) looks nice, and yes, the Flow is used by a WikiWorks customer wiki at the moment ( actually maybe not one but few ), and yes, afaik there is no migration tool available yet. Do we want to be the ones who will create it?

**Comment by yaronkoren** [comment]
That's unfortunate. Yes, perhaps we should be creating such a script, assuming one or more customers would pay for it. But this discussion should probably move elsewhere, since this is no longer a Canasta issue but a WikiWorks issue.

**Comment by yaronkoren** [comment]
Well, since we have been talking about it here: it turns out that StructuredDiscussions already includes a script, [convertToText.php](https://phabricator.wikimedia.org/diffusion/EFLW/browse/master/maintenance/convertToText.php), which takes in the discussion on a single talk page (or any kind of page, really) and converts it all to wikitext. Maybe this is a good enough solution?

**Review by yaronkoren — APPROVED** [review]

**Comment by yaronkoren** [comment]
Oh wait, I just meant to approve the "--skip-config-validation" change - I didn't meant to approve this whole PR.

**Comment by vedmaka** [comment]
We should cherry-pick the --skip-config-validation commit

**Comment by yaronkoren** [comment]
Closing this PR, even though it's just a draft. Hopefully this will not cause any problems.

**Pull request closed without merging**
